# Generated by Django 4.2.13 on 2026-06-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
        migrations.AlterField(
            model_name='booking',
            name='semester',
            field=models.CharField(choices=[('Semester 1 2025/2026', 'Semester 1 2025/2026'), ('Semester 2 2025/2026', 'Semester 2 2025/2026'), ('Semester 1 2026/2027', 'Semester 1 2026/2027'), ('Semester 2 2026/2027', 'Semester 2 2026/2027')], max_length=50),
        ),
    ]
